# Based on:
#   https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
#   https://github.com/iwatake2222/cpp_project_in_github/blob/master/.github/workflows/cmake_x64.yml
name: Build with CMake on pushed tags

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the configurations
      matrix:
        os: [windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            configure_options: -G "Visual Studio 17 2022" -A x64 -T ClangCL
            target_triplet: x64-windows-static-md
            executable_name: ExampleProject.exe
            artifact_name: ExampleProject_windows_x64.zip

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake --preset=vcpkg-github
          ${{ matrix.configure_options }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DVCPKG_TARGET_TRIPLET=${{ matrix.target_triplet }}

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Create artifacts
        shell: bash
        run: |
          ls  '${{github.workspace}}/build'
          if [[ "${{ matrix.os }}" == "windows-latest" ]]
          then
            7z a ${{ matrix.artifact_name }} '${{github.workspace}}/build/Release/${{ matrix.executable_name }}'
          fi
          ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ matrix.artifact_name }}
